Trying dirty upgrades.  (No data wipe.)

diff --git a/android_tools b/android_tools
--- a/android_tools
+++ b/android_tools
@@ -328,11 +328,11 @@ function install_image {
 
   output "Beginning installation."
 
-  install_script_file='flash-all.sh'
-  install_script_pure_file='flash-all-pure.sh'
-  install_script_real_file='flash-all-real.sh'
-  grep -Ev ^#'|'^\$ $install_script_file > $install_script_pure_file
-  cat > $install_script_real_file << EOF
+  install_script='flash-all.sh'
+  install_script_reduced='flash-all-reduced.sh'
+  install_script_expected='flash-all-expected.sh'
+  grep -Ev ^#'|'^\$ $install_script > $install_script_reduced
+  cat > $install_script_expected << EOF
 fastboot flash bootloader bootloader-hammerhead-*.img
 fastboot reboot-bootloader
 sleep 5
@@ -349,22 +349,20 @@ EOF
       s/radio-hammerhead-[a-z0-9]*-[0-9\.]*\.img/radio-hammerhead-\*\.img/;
       s/image-hammerhead-[a-z0-9]*\.zip/image-hammerhead-\*\.zip/;
     ' \
-    $install_script_pure_file
+    $install_script_reduced
 
   # This might be paranoid.  The script gets downloaded over https.  (Trust
   # Google with root on host system?)  I don't think the script changes much
   # anyway.
-  if ! diff $install_script_pure_file $install_script_real_file >/dev/null; then
-    error_output "The install script changed.  You may wish to review it, at:"
-    error_output "  ${install_script_real_file}"
-    error_output "...and/or the"
-    error_output "procedure at:  "
+  if ! diff $install_script_reduced $install_script_expected >/dev/null; then
+    error_output "The install script changed.  You may wish to review the new script, at:"
+    error_output "  ${install_script}"
+    error_output "Also see:"
     error_output "  https://developers.google.com/android/nexus/images"
-    error_output "...then edit this script appropriately."
+    error_output "Then edit this script appropriately."
     return 1
   fi
 
-  # flash-all.sh contents, or similar
   output "Flashing bootloader."
   fastboot flash bootloader bootloader-hammerhead-*.img \
                                                 || fail "Failed to flash bootloader."
@@ -375,7 +373,11 @@ EOF
   reboot_from_fastboot_to_fastboot              || fail "Failed to reboot to fastboot."
   sleep 1
   output "Flashing image."
-  fastboot -w update image-hammerhead-*.zip     || fail "Failed to flash image."
+  # Maybe we don't need to wipe out userdata on minor upgrades.
+  if test $latest_major_version = $start_major_version; then wipe_flag=''
+  else wipe_flag='-w'
+  fi
+  fastboot "${wipe_flag}" update image-hammerhead-*.zip     || fail "Failed to flash image."
 
   output "Installation complete."
   
