Added one more file to replace with a symlink to /dev/null .  Sorted some lines.  Adjusted some output messages.

diff --git a/image_pi_card b/image_pi_card
--- a/image_pi_card
+++ b/image_pi_card
@@ -100,19 +100,20 @@ configure_os() {
     || fail "Failed to write root password."
 
   for file in \
+    /mnt/card/etc/profile.d/armbian-check-first-login-reboot.sh \
+    /mnt/card/etc/profile.d/armbian-check-first-login.sh \
+    /mnt/card/etc/ssh/ssh_host_*_key* \
+    /mnt/card/etc/systemd/network/99-default.link
+    /mnt/card/etc/systemd/system/default.target.wants/ssh.service \
+    /mnt/card/etc/systemd/system/multi-user.target.wants/NetworkManager.service \
+    /mnt/card/etc/systemd/system/multi-user.target.wants/armbian-firstrun-config.service \
+    /mnt/card/etc/systemd/system/multi-user.target.wants/armbian-firstrun-config.service \
+    /mnt/card/lib/systemd/system/NetworkManager.service \
     /mnt/card/lib/systemd/system/armbian-firstrun-config.service \
     /mnt/card/lib/systemd/system/armbian-firstrun.service \
     /mnt/card/lib/systemd/system/armbian-resize-filesystem.service \
-    /mnt/card/lib/systemd/system/NetworkManager.service \
-    /mnt/card/usr/lib/armbian/armbian-firstrun-config \
     /mnt/card/usr/lib/armbian/armbian-firstrun \
-    /mnt/card/etc/systemd/system/multi-user.target.wants/armbian-firstrun-config.service \
-    /mnt/card/etc/profile.d/armbian-check-first-login.sh \
-    /mnt/card/etc/profile.d/armbian-check-first-login-reboot.sh \
-    /mnt/card/etc/systemd/system/multi-user.target.wants/armbian-firstrun-config.service \
-    /mnt/card/etc/systemd/system/multi-user.target.wants/NetworkManager.service \
-    /mnt/card/etc/systemd/system/default.target.wants/ssh.service \
-    /mnt/card/etc/ssh/ssh_host_*_key* \
+    /mnt/card/usr/lib/armbian/armbian-firstrun-config \
     /mnt/card/var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/NetworkManager.service \
   ; do
     sudo rm -f $file \
@@ -120,6 +121,7 @@ configure_os() {
   done
 
   for file in \
+    /mnt/card/etc/systemd/network/99-default.link
     /mnt/card/lib/systemd/system/armbian-firstrun-config.service \
     /mnt/card/lib/systemd/system/armbian-firstrun.service \
     /mnt/card/lib/systemd/system/armbian-resize-filesystem.service \
@@ -128,7 +130,7 @@ configure_os() {
     /mnt/card/usr/lib/armbian/armbian-firstrun \
   ; do
     sudo ln -s /dev/null $file \
-      || fail "Failed to mask service file:  '${file}'"
+      || fail "Failed to replace file with symlink to /dev/null:  '${file}'"
   done
 
   read wpa_psk < ~/sensitive/accounts/network/puppies/wpa_psk.txt \
@@ -173,7 +175,7 @@ UsePam no
 EOF
 
   sudo mkdir -p /mnt/card/etc/systemd/system/default.target.wants \
-    || fail "Failed to create some systemd bullshit directory."
+    || fail "Failed to create some systemd directory."
   sudo ln -s /lib/systemd/system/ssh.service /mnt/card/etc/systemd/system/default.target.wants/ssh.service \
     || fail "Failed to write ssh service file."
 
