I'm tired of seeing a second password prompt when working with larger/slower SD cards.

diff --git a/image_pi_card b/image_pi_card
--- a/image_pi_card
+++ b/image_pi_card
@@ -17,6 +17,13 @@ get_root() {
 }
 
 
+keep_root() {
+  while sleep 60; do
+    sudo -v
+  done
+}
+
+
 target_host_name="${1}"
 case "${target_host_name}" in
   partybus)
@@ -25,6 +32,8 @@ case "${target_host_name}" in
     ip_address=192.168.11.64
     label=log
     mount_point=/var/log
+    wired_interface=eth0
+    wireless_interface=wlan0
     ;;
   files)
     card_device=/dev/sdc
@@ -33,6 +42,11 @@ case "${target_host_name}" in
     ip_address=192.168.11.62
     label=log
     mount_point=/var/log
+    # We use the systemd method to disable "predictable" (and yet insanely hard
+    # to predict) interface naming, and systemd seems to be in use, yet this
+    # abomination is the default name of the interface:
+    wired_interface=enx001e0636856d
+    wireless_interface=wlan0
     ;;
   spy)
     card_device=/dev/sdc
@@ -40,6 +54,8 @@ case "${target_host_name}" in
     #ip_address=192.168.11.?
     label=motion
     mount_point=/var/lib/motion
+    wired_interface=eth0
+    wireless_interface=wlan0
     fail "spy is not configured"
     ;;
   *)
@@ -89,6 +105,10 @@ configure_os() {
   echo "LABEL=${label} ${mount_point} f2fs defaults,noatime,nodiratime 0 2" | sudo tee -a /mnt/card/etc/fstab \
     || fail "Failed to write fstab."
 
+  # This is for debugging.  log2ram is probably good for sd card life.
+  sudo sed -i 's/^ENABLED=.*$/ENABLED=false/' /mnt/card/etc/default/armbian-ramlog \
+    || fail "Failed to disabled log2ram."
+
   # Do this manually (once):
   #sudo passwd root-at-host
 
@@ -135,8 +155,8 @@ configure_os() {
 
   read wpa_psk < ~/sensitive/accounts/network/puppies/wpa_psk.txt \
     || fail "Failed to read WPA PSK."
-  sudo tee /mnt/card/etc/network/interfaces.d/wlan0 << EOF
-iface wlan0 inet static
+  sudo tee /mnt/card/etc/network/interfaces.d/"${wireless_interface}" << EOF
+iface ${wireless_interface} inet static
     wpa-essid           puppies
     wpa-psk             $wpa_psk
     address             $ip_address
@@ -146,10 +166,10 @@ iface wlan0 inet static
     dns-search          neuronpointer.net
 EOF
   if ! test 0 == "${?}"; then
-    fail "Failed to write:  interfaces.d/wlan0" 
+    fail "Failed to write:  interfaces.d/${wireless_interface}" 
   fi
-  sudo tee /mnt/card/etc/network/interfaces.d/eth0 << EOF
-iface eth0 inet static
+  sudo tee /mnt/card/etc/network/interfaces.d/"${wired_interface}" << EOF
+iface ${wired_interface} inet static
     address             $ip_address
     netmask             255.255.255.0
     gateway             192.168.11.1
@@ -157,9 +177,9 @@ iface eth0 inet static
     dns-search          neuronpointer.net
 EOF
   if ! test 0 == "${?}"; then
-    fail "Failed to write:  interfaces.d/eth0" 
+    fail "Failed to write:  interfaces.d/${wired_interface}" 
   fi
-  echo 'auto eth0' | sudo tee -a /mnt/card/etc/network/interfaces \
+  echo "auto ${wired_interface}" | sudo tee -a /mnt/card/etc/network/interfaces \
     || fail "Failed to write to interfaces file."
 
   
@@ -187,10 +207,15 @@ EOF
     || fail "Failed to write SSH host key (private)."
   cat ~/control_center/ansible/inventory/hosts/${target_host_name}/files/ssh_keys/ssh_host_rsa_key.pub | sudo tee /mnt/card/etc/ssh/ssh_host_rsa_key.pub \
     || fail "Failed to write SSH host key (public)."
+
+  sudo rsync -a "/mnt/card${mount_point}/" /mnt/card2/ \
+    || fail "Failed to sync contents of mount point to big partition."
 }
 
 main() {
   get_root
+  keep_root &
+  sudo_loop_pid=$!
   if mountpoint /mnt/card > /dev/null 2>&1; then
     sudo umount /mnt/card \
       || fail "Failed to preparatively unmount /mnt/card."
@@ -198,10 +223,17 @@ main() {
   write_image
   create_big_volume
   sudo mount $root_partition /mnt/card \
-    || fail "Failed to mount card."
+    || fail "Failed to mount root partition."
+  sudo mount $big_partition /mnt/card2 \
+    || fail "Failed to mount big partition."
   configure_os
+  sudo umount /mnt/card2 \
+    || fail "Failed to unmount big partition."
   sudo umount /mnt/card \
-    || fail "Failed to unmount card."
+    || fail "Failed to unmount root partition."
+  kill $sudo_loop_pid
+  timeout 5 wait $sudo_loop_pid
+  kill -9 $sudo_loop_pid
 }
 
 
