Trivial change.

diff --git a/update_nexus_5 b/update_nexus_5
--- a/update_nexus_5
+++ b/update_nexus_5
@@ -107,7 +107,7 @@ EOF
   # Google with root on host system?)  I don't think the script changes much
   # anyway.
   if ! diff $install_script_pure_file $install_script_real_file; then
-    echo -e "  Error:  The install script changed.  You may wish to review it, and/or the\n  procedure at:  https://developers.google.com/android/nexus/images" >&2
+    echo -e "  Error:  The install script changed.  You may wish to review it, and/or the\n  procedure at:  https://developers.google.com/android/nexus/images\n  ...then edit this script appropriately." >&2
     exit 1
   fi
 
