Tested for 6.0 to 6.0 same-grade.  Seems worky.

diff --git a/update_nexus_5 b/update_nexus_5
--- a/update_nexus_5
+++ b/update_nexus_5
@@ -16,7 +16,9 @@ backup_file=${backup_dir}/${now}.ab
 # -all:  This just specifies "all packages" as the target.
 # -nosystem:  System settings would be nice, but compatibility is not
 # guaranteed, since the system is being upgraded.
-backup_options="-f $backup_file -apk -all -nosystem -shared"
+backup_options_5="-f ${backup_file} -apk -all -nosystem -shared"
+backup_options_6="-f ${backup_file} -all"
+output_prefix='| '
 
 function main {
   latest_image_link=$(latest_image_link)
@@ -25,37 +27,67 @@ function main {
   latest_twrp_image_link=$(latest_twrp_image_link)
   twrp_image_file=$(echo $latest_twrp_image_link | sed 's/^.*\///')
   start_phone_count=$(count_phones)
+  start_fastboot_count=$(count_fastboots)
 
-  cd /tmp/                      || fail "Failed to enter directory:  /tmp"
-  mkdir -p ${backup_dir}        || fail "Failed to create backup directory:  ${backup_dir}"
-  greet                         || fail "Failed to greet the user."
-  cycle_adb                     || fail "Failed to cycle adb."
-  download_latest_image         || fail "Failed to download stock image."
-  download_latest_twrp_image    || fail "Failed to download TWRP recovery image."
-  backup_data                   || fail "Failed to backup data."
-  unpack_image                  || fail "Failed to unpack image."
-  install_image                 || fail "Failed to install image."
-  install_modified_boot         || fail "Failed to install modified boot volume."
-  install_twrp_image            || fail "Failed to install TWRP recovery image."
-  restore_data                  || fail "Failed to restore application data."
-  reboot_phone                  || fail "Failed to reboot."
+  cd /tmp/                                      || fail "Failed to enter directory:  /tmp"
+  mkdir -p ${backup_dir}                        || fail "Failed to create backup directory:  ${backup_dir}"
+  greet                                         || fail "Failed to greet the user."
+  cycle_adb                                     || fail "Failed to cycle adb."
+
+  start_version=$(adb shell getprop ro.build.version.release)
+  start_major_version=$(echo $start_version | sed 's/\..*//g')
+
+  echo $start_major_version | grep -q '^[0-9]$' || fail "Failed to ascertain starting version."
+
+  download_latest_image                         || fail "Failed to download stock image."
+  download_latest_twrp_image                    || fail "Failed to download TWRP recovery image."
+  backup_data                                   || fail "Failed to backup data."
+  unpack_image                                  || fail "Failed to unpack image."
+  reboot_to_fastboot                            || fail "Failed to reboot to fastboot."
+  install_image                                 || fail "Failed to install image."
+
+  output "Once you provide wifi and Google credentials, Google should start restoring apps."
+  prompt "When Google finishes restoring apps and USB debugging is enabled, press Enter to continue."
+
+  reboot_to_fastboot                            || fail "Failed to reboot to fastboot."
+  install_modified_boot                         || fail "Failed to install modified boot volume."
+  install_twrp_image                            || fail "Failed to install TWRP recovery image."
+
+# This seems nice but doesn't work.  Once you've booted Android, the recovery
+# has already been overwritten.
+#  reboot_from_fastboot                          || fail "Failed to reboot from fastboot."
+#  wait_for_phone
+#  reboot_to_recovery                            || fail "Failed to reboot to recovery."
+
+  prompt "Please use the volume and power buttons to enter Recovery mode, then press Enter."
+  prompt "Accept the proposal to modify the system volume, then hit Enter."
+  prompt "Hit \"Reboot\", then \"System\", then come back and hit Enter."
+  prompt "Accept the proposal to root the phone, then come back and hit Enter."
+
+  wait_for_phone
+
+  output "Give it a chance to finish booting.  (30s)"
+  sleep 30
+
+  restore_data                                  || fail "Failed to restore application data."
+  reboot_phone                                  || fail "Failed to reboot."
 
   bye
 }
 
 
 function output {
-  echo -e "| ${1}"
+  echo "${output_prefix}${1}"
 }
 
 
 function error_output {
-  echo -e "| ERROR:  ${1}" >&2
+  echo "${output_prefix}ERROR:  ${1}"
 }
 
 
 function fail {
-  error_output $1
+  error_output "${1}"
   exit 1
 }
 
@@ -63,17 +95,47 @@ function fail {
 function prompt {
   # Clear stdin.
   while read -r -t 0; do read -r; done
-  read -p "| ${1}  " response
+  read -p "${output_prefix}${1}  " response
 }
 
 
 function reboot_phone {
   output "Rebooting phone."
-  adb reboot
+  adb reboot || fail "Failed to adb reboot."
+}
+
+
+function reboot_from_fastboot {
+  output "Rebooting phone."
+  fastboot reboot || fail "Failed to fastboot reboot."
+}
+
+
+
+
+function reboot_from_fastboot_to_fastboot {
+  output "Rebooting to fastboot."
+  fastboot reboot-bootloader || fail "Failed to fastboot reboot-bootloader"
+}
+
+function reboot_to_recovery {
+  output "Rebooting to recovery."
+  adb reboot recovery || fail "Failed to adb reboot recovery."
+}
+
+
+function reboot_to_fastboot {
+  output "Rebooting to fastboot."
+  adb reboot-bootloader || fail "Failed to reboot to fastboot."
 }
 
 
 function backup_data {
+  backup_options=$backup_options_5
+  if test $start_major_version -gt 5; then
+    backup_options=$backup_options_6
+  fi
+
   while true; do
     output "Backing up data to:  ${backup_file}"
     adb backup $backup_options
@@ -293,38 +355,32 @@ EOF
   # Google with root on host system?)  I don't think the script changes much
   # anyway.
   if ! diff $install_script_pure_file $install_script_real_file; then
-    error_output "The install script changed.  You may wish to review it, and/or the\n  procedure at:  https://developers.google.com/android/nexus/images\n  ...then edit this script appropriately."
+    error_output "The install script changed.  You may wish to review it, and/or the"
+    error_output "procedure at:  https://developers.google.com/android/nexus/images"
+    error_output "...then edit this script appropriately."
     return 1
   fi
 
-  adb reboot bootloader
-
-  # flash-all.sh contents
+  # flash-all.sh contents, or similar
   output "Flashing bootloader."
   fastboot flash bootloader bootloader-hammerhead-*.img || fail "Failed to flash bootloader."
-  fastboot reboot-bootloader || fail "Failed to reboot to bootloader."
-  sleep 5
+  reboot_from_fastboot_to_fastboot || fail "Failed to reboot to fastboot."
+  sleep 1
   output "Flashing radio."
   fastboot flash radio radio-hammerhead-*.img || fail "Failed to flash radio."
-  fastboot reboot-bootloader || fail "Failed to reboot to bootloader."
-  sleep 5
+  reboot_from_fastboot_to_fastboot || fail "Failed to reboot to fastboot."
+  sleep 1
   output "Flashing image."
   fastboot -w update image-hammerhead-*.zip || fail "Failed to flash image."
 
-  output "Installation complete.  The first boot should take about ten minutes."
-  output "Re-enable USB debugging and wait until all apps have updated."
-  output "(Watch My Apps in the Play Store for progress.)"
-  output "Then press Enter to continue."
-  read
-
-  cd - || fail "Failed to return from image directory."
+  output "Installation complete."
+  
+  cd - >/dev/null || fail "Failed to return from image directory."
 }
 
 
 function install_modified_boot {
   output "Installing modified boot volume."
-
-  adb reboot-bootloader || fail "Failed to reboot to bootloader."
 
   fastboot flash boot ~/images/nexus5/modified_boot_for_selinux_compatible_su/boot.img || fail "Failed to flash modified boot."
 
@@ -338,29 +394,37 @@ function install_twrp_image {
   fastboot flash recovery $twrp_image_file || fail "Failed to flash twrp image:  ${twrp_image_file}"
 
   output "TWRP recovery image installation successful."
-
-  fastboot reboot || fail "Failed to fastboot reboot."
-  wait_for_phone
-  adb reboot recovery || fail "Failed to reboot to recovery."
-
-  output "Please answer the prompt to allow modification of system volume."
-  output "Then hit \"Reboot\", then \"System\"."
-  output "When prompted, accept the offer to install SuperSu."
 }
 
 
 function wait_for_phone {
   output "Waiting for phone..."
-  while test $(count_phones) -lt $start_phone_count; do
+  phone_count=$(count_phones)
+  while test $phone_count -lt $start_phone_count; do
     sleep 1
-    output "..."
+    output "... $phone_count / $start_phone_count devices detected."
   done
   output "Phone is back."
 }
 
 
 function count_phones {
-   echo $(( $(adb devices | wc -l) - 2 ))
+  echo $(( $(adb devices | wc -l) - 2 ))
+}
+
+
+function wait_for_fastboot {
+  output "Waiting for fastboot..."
+  while test $(count_fastboots) -lt $start_fastboot_count; do
+    sleep 1;
+    output "..."
+  done
+  output "Phone is back."
+}
+
+
+function count_fastboots {
+  echo $(fastboot devices | wc -l)
 }
 
 
